// Auto-generated by scripts/build-agent-stats.js — DO NOT EDIT
// Last updated: 2026-07-04T11:21:49+08:00
const AGENT_STATS = {
  "lastUpdated": "2026-07-04T11:21:49+08:00",
  "grade_rule_cn": "统计：全赢1 · 赢半0.5 · 输半0.5 · 走水不计；单场✓/✗仍按不败即中（含赢半）",
  "days_graded": 7,
  "days_pending": 0,
  "aggregate": {
    "spread": {
      "hit": 11,
      "miss": 6.5,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 52.4
    },
    "totals": {
      "hit": 9.5,
      "miss": 9,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 45.2
    },
    "primary": {
      "hit": 12,
      "miss": 5.5,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 57.1,
      "label_cn": "★倾向项"
    },
    "secondary": {
      "hit": 8.5,
      "miss": 10,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 40.5,
      "label_cn": "非倾向项"
    },
    "high_confidence": {
      "n": 11,
      "ids": [
        "m67",
        "m69",
        "m70",
        "m72",
        "m76",
        "m74",
        "m75",
        "m79",
        "m81",
        "m84",
        "m86"
      ],
      "spread": {
        "hit": 6,
        "miss": 2.5,
        "push": 1,
        "pending": 0,
        "legs": 10,
        "n": 10,
        "pct": 60
      },
      "totals": {
        "hit": 5,
        "miss": 4.5,
        "push": 0,
        "pending": 0,
        "legs": 11,
        "n": 11,
        "pct": 45.5
      },
      "primary": {
        "hit": 7,
        "miss": 1.5,
        "push": 1,
        "pending": 0,
        "legs": 10,
        "n": 10,
        "pct": 70
      }
    }
  },
  "days": [
    {
      "day": 17,
      "date": "2026-06-28",
      "graded_at": "2026-07-02T05:16:42.215Z",
      "spread": {
        "hit": 4,
        "miss": 1,
        "push": 1,
        "pending": 0,
        "legs": 5,
        "pct": 80,
        "n": 5
      },
      "totals": {
        "hit": 2,
        "miss": 4,
        "push": 0,
        "pending": 0,
        "legs": 6,
        "pct": 33.3,
        "n": 6
      },
      "primary": {
        "hit": 4,
        "miss": 1,
        "push": 1,
        "pending": 0,
        "legs": 5,
        "pct": 80,
        "label_cn": "倾向项（★）",
        "n": 5
      },
      "high_confidence": {
        "n": 4,
        "ids": [
          "m67",
          "m69",
          "m70",
          "m72"
        ],
        "spread": {
          "hit": 3,
          "miss": 0,
          "push": 1,
          "pending": null,
          "legs": 3,
          "pct": 100,
          "n": 3
        },
        "totals": {
          "hit": 1,
          "miss": 3,
          "push": 0,
          "pending": null,
          "legs": 4,
          "pct": 25,
          "n": 4
        },
        "primary": {
          "hit": 3,
          "miss": 0,
          "push": 1,
          "pending": null,
          "legs": 3,
          "pct": 100,
          "n": 3
        }
      }
    },
    {
      "day": 18,
      "date": "2026-06-29",
      "graded_at": "2026-07-02T05:16:42.252Z",
      "spread": {
        "hit": 1,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "legs": 1,
        "pct": 100,
        "n": 1
      },
      "totals": {
        "hit": 1,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "legs": 1,
        "pct": 100,
        "n": 1
      },
      "primary": {
        "hit": 1,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "legs": 1,
        "pct": 100,
        "label_cn": "倾向项（★）",
        "n": 1
      },
      "high_confidence": null
    },
    {
      "day": 19,
      "date": "2026-06-30",
      "graded_at": "2026-07-02T05:16:42.277Z",
      "spread": {
        "hit": 1.5,
        "miss": 0.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 50,
        "n": 3
      },
      "totals": {
        "hit": 2,
        "miss": 0.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 66.7,
        "n": 3
      },
      "primary": {
        "hit": 2,
        "miss": 0.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 66.7,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 3,
        "ids": [
          "m76",
          "m74",
          "m75"
        ],
        "spread": {
          "hit": 1.5,
          "miss": 0.5,
          "push": 0,
          "pending": null,
          "legs": 3,
          "pct": 50,
          "n": 3
        },
        "totals": {
          "hit": 2,
          "miss": 0.5,
          "push": 0,
          "pending": null,
          "legs": 3,
          "pct": 66.7,
          "n": 3
        },
        "primary": {
          "hit": 2,
          "miss": 0.5,
          "push": 0,
          "pending": null,
          "legs": 3,
          "pct": 66.7,
          "n": 3
        }
      }
    },
    {
      "day": 20,
      "date": "2026-07-01",
      "graded_at": "2026-07-02T05:16:42.299Z",
      "spread": {
        "hit": 0.5,
        "miss": 2,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 16.7,
        "n": 3
      },
      "totals": {
        "hit": 1.5,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 50,
        "n": 3
      },
      "primary": {
        "hit": 2,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 66.7,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 1,
        "ids": [
          "m79"
        ],
        "spread": {
          "hit": 0,
          "miss": 1,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 0,
          "n": 1
        },
        "totals": {
          "hit": 0.5,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 50,
          "n": 1
        },
        "primary": {
          "hit": 0.5,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 50,
          "n": 1
        }
      }
    },
    {
      "day": 21,
      "date": "2026-07-02",
      "graded_at": "2026-07-03T11:49:22.383Z",
      "spread": {
        "hit": 1.5,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 50,
        "n": 3
      },
      "totals": {
        "hit": 1,
        "miss": 2,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 33.3,
        "n": 3
      },
      "primary": {
        "hit": 0.5,
        "miss": 2,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 16.7,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 1,
        "ids": [
          "m81"
        ],
        "spread": {
          "hit": 0,
          "miss": 1,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 0,
          "n": 1
        },
        "totals": {
          "hit": 0,
          "miss": 1,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 0,
          "n": 1
        },
        "primary": {
          "hit": 0,
          "miss": 1,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 0,
          "n": 1
        }
      }
    },
    {
      "day": 22,
      "date": "2026-07-03",
      "graded_at": "2026-07-03T11:49:22.527Z",
      "spread": {
        "hit": 1,
        "miss": 1.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 33.3,
        "n": 3
      },
      "totals": {
        "hit": 1,
        "miss": 0.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 33.3,
        "n": 3
      },
      "primary": {
        "hit": 1,
        "miss": 1.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 33.3,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 1,
        "ids": [
          "m84"
        ],
        "spread": {
          "hit": 1,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 100,
          "n": 1
        },
        "totals": {
          "hit": 0.5,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 50,
          "n": 1
        },
        "primary": {
          "hit": 1,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 100,
          "n": 1
        }
      }
    },
    {
      "day": 23,
      "date": "2026-07-04",
      "graded_at": "2026-07-04T11:21:49.287Z",
      "spread": {
        "hit": 1.5,
        "miss": 0.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 50,
        "n": 3
      },
      "totals": {
        "hit": 1,
        "miss": 1,
        "push": 1,
        "pending": 0,
        "legs": 2,
        "pct": 50,
        "n": 2
      },
      "primary": {
        "hit": 1.5,
        "miss": 0.5,
        "push": 0,
        "pending": 0,
        "legs": 3,
        "pct": 50,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 1,
        "ids": [
          "m86"
        ],
        "spread": {
          "hit": 0.5,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 50,
          "n": 1
        },
        "totals": {
          "hit": 1,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 100,
          "n": 1
        },
        "primary": {
          "hit": 0.5,
          "miss": 0,
          "push": 0,
          "pending": null,
          "legs": 1,
          "pct": 50,
          "n": 1
        }
      }
    }
  ],
  "pending": [],
  "evaluation": {
    "label_cn": "Agent 双选评估",
    "match_count": 21,
    "grade_rule_cn": "统计：全赢1 · 赢半0.5 · 输半0.5 · 走水不计；单场✓/✗仍按不败即中（含赢半）",
    "spread": {
      "hit": 11,
      "miss": 6.5,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 52.4,
      "label_cn": "让球盘胜率",
      "desc_cn": "全部 21 场 Agent 双选 · 让球项"
    },
    "totals": {
      "hit": 9.5,
      "miss": 9,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 45.2,
      "label_cn": "大小盘胜率",
      "desc_cn": "全部 21 场 Agent 双选 · 大小项"
    },
    "primary": {
      "hit": 12,
      "miss": 5.5,
      "push": 1,
      "pending": 0,
      "legs": 21,
      "n": 21,
      "pct": 57.1,
      "label_cn": "倾向盘胜率",
      "desc_cn": "每场标★方向（让球或大小）"
    },
    "high_confidence": {
      "match_count": 11,
      "ids": [
        "m67",
        "m69",
        "m70",
        "m72",
        "m76",
        "m74",
        "m75",
        "m79",
        "m81",
        "m84",
        "m86"
      ],
      "primary": {
        "hit": 7,
        "miss": 1.5,
        "push": 1,
        "pending": 0,
        "legs": 10,
        "n": 10,
        "pct": 70,
        "label_cn": "大信心胜率",
        "desc_cn": "大信心场 · ★倾向项命中率"
      }
    }
  },
  "knockout": {
    "label_cn": "32强 · Agent 双选",
    "match_count": 13,
    "ids": [
      "m67",
      "m68",
      "m69",
      "m70",
      "m71",
      "m72",
      "m73",
      "m74",
      "m75",
      "m76",
      "m77",
      "m78",
      "m79"
    ],
    "spread": {
      "hit": 7,
      "miss": 3.5,
      "legs": 12,
      "n": 12,
      "pct": 58.3
    },
    "totals": {
      "hit": 6.5,
      "miss": 5.5,
      "legs": 13,
      "n": 13,
      "pct": 50
    },
    "primary": {
      "hit": 9,
      "miss": 1.5,
      "legs": 12,
      "n": 12,
      "pct": 75,
      "label_cn": "★倾向项"
    },
    "both_hit": {
      "n": 4,
      "pct": 30.8
    },
    "at_least_one": {
      "n": 12,
      "pct": 92.3
    },
    "all_legs": {
      "hit": 13.5,
      "n": 25,
      "pct": 54
    }
  },
  "byId": {
    "m67": {
      "day": 17,
      "match": "Panama vs England",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "巴拿马 +2/2.5 @1.02",
        "reason_cn": "FIFA 官方英格兰 5 轮换（Rice/Mainoo/Foden 替补）；xG 客 2.08→1.90。胜约 65% 但穿 -2.25 约 25%；0-1/0-2 仍守住。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "0-2 · 净胜 -2 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3/3.5",
        "reason_cn": "模型公允总进球约 2.0，现线 3.25 偏高约 0.75 球；超线概率约 40%，小水 1.02 在卖大球叙事。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "0-2 总2 · 线 3.25 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "full_win",
      "totals_outcome": "full_win",
      "grade_note_spread": "0-2 · 净胜 -2 · 全赢",
      "grade_note_totals": "0-2 总2 · 线 3.25 · 全赢",
      "actual_score": "0-2",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m68": {
      "day": 17,
      "match": "Croatia vs Ghana",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "dog",
        "label_cn": "加纳 +0.5 守住",
        "reason_cn": "加纳 4 分已锁前二可接受平局；克罗地亚 3 分须胜易急躁；xG 1.42 vs 1.38 均势，首推 1-1。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-1 · 净胜 +1 · 全输"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2",
        "reason_cn": "2 整球线下 ≤2 球即全赢；模型有平局/小胜路径，大球 0.86 略诱但出线博弈下闷战概率不低。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-1 总3 · 线 2 · 全输"
      },
      "primary_hit": false,
      "spread_hit": false,
      "totals_hit": false,
      "spread_outcome": "full_lose",
      "totals_outcome": "full_lose",
      "grade_note_spread": "2-1 · 净胜 +1 · 全输",
      "grade_note_totals": "2-1 总3 · 线 2 · 全输",
      "actual_score": "2-1",
      "outcome": {
        "key": "both_miss",
        "cn": "★让球盘与大小球均未中",
        "analytics_cn": "全盘失误，需复盘模型、盘路与倾向规则",
        "primary_hit": false,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m69": {
      "day": 17,
      "match": "Algeria vs Austria",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "fav",
        "label_cn": "奥地利 PK（-0）@0.84",
        "reason_cn": "已锁前二 · 输球亦出线；阿尔须胜但模型平局 +9% → 不败约 73%。无输半档，符合先不输。",
        "hit": true,
        "outcome": "push",
        "grade_note": "3-3 · 净胜 0 · 走水"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 1.5/2 @0.82",
        "reason_cn": "副项 · 皇冠小 0.82 + 默契战；但 1-1 输半、模型约 68% 超线，不作★。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "3-3 总6 · 线 1.75 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "push",
      "totals_outcome": "full_lose",
      "grade_note_spread": "3-3 · 净胜 0 · 走水",
      "grade_note_totals": "3-3 总6 · 线 1.75 · 全输",
      "actual_score": "3-3",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m70": {
      "day": 17,
      "match": "Jordan vs Argentina",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "约旦 +2/2.5 守住",
        "reason_cn": "阿根廷 6 分已出线必轮换；模型胜 77% 但穿 -2.25 校准后约 49%；升盘 0.99 为限损而非加强。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "1-3 · 净胜 -2 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3",
        "reason_cn": "3 整球走水多；大球 0.83 便宜但模型公允约 2.75，轮换队常见 2-0/3-0 卡线而非开放对攻。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "1-3 总4 · 线 3 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "full_win",
      "totals_outcome": "full_lose",
      "grade_note_spread": "1-3 · 净胜 -2 · 全赢",
      "grade_note_totals": "1-3 总4 · 线 3 · 全输",
      "actual_score": "1-3",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m71": {
      "day": 17,
      "match": "Colombia vs Portugal",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "dog",
        "label_cn": "哥伦比亚 +0.5 守住",
        "reason_cn": "哥伦 6 分平局即头名；葡萄牙 4 分须胜但 0.98 抬水未追；xG 1.55 vs 1.58 均势。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "0-0 · 净胜 0 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5/3",
        "reason_cn": "已出线双方 xG 略降；小水 0.89 偏小，迈阿密湿热下更可能 1-1/2-1 而非开放对攻。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "0-0 总0 · 线 2.75 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "full_win",
      "totals_outcome": "full_win",
      "grade_note_spread": "0-0 · 净胜 0 · 全赢",
      "grade_note_totals": "0-0 总0 · 线 2.75 · 全赢",
      "actual_score": "0-0",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m72": {
      "day": 17,
      "match": "Congo DR vs Uzbekistan",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "fav",
        "label_cn": "刚果(金) -0.5/1",
        "reason_cn": "双方须胜无控分；盘口向 xG 1.48 vs 0.72 修正，刚果 -0.75 与模型一致，主场生死战信实力方小胜。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "3-1 · 净胜 +2 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2/2.5",
        "reason_cn": "xG 合计约 2.2，线 2.25 中性；乌兹别克守势下 1-0/2-0 比大比分更合理。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "3-1 总4 · 线 2.25 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "full_win",
      "totals_outcome": "full_lose",
      "grade_note_spread": "3-1 · 净胜 +2 · 全赢",
      "grade_note_totals": "3-1 总4 · 线 2.25 · 全输",
      "actual_score": "3-1",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m73": {
      "day": 18,
      "match": "South Africa vs Canada",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "dog",
        "label_cn": "南非 +0/0.5 @0.98",
        "reason_cn": "A 组次席 4 分出线 · 小组赛 2 失球偏稳；加拿大须破局但 -0/0.5 低水未必穿。模型平局约 32%。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "0-1 · 净胜 -1 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2/2.5",
        "reason_cn": "32 强首轮双方偏谨慎 · 模型总 xG 约 2.1 · 2/2.5 线下 ≤2 球即全赢。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "0-1 总1 · 线 2.25 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "full_win",
      "totals_outcome": "full_win",
      "grade_note_spread": "0-1 · 净胜 -1 · 全赢",
      "grade_note_totals": "0-1 总1 · 线 2.25 · 全赢",
      "actual_score": "0-1",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m76": {
      "day": 19,
      "match": "Brazil vs Japan",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "日本 +0.5/1 @0.88",
        "reason_cn": "巴西 0.96 仍高水 · 日本 F 组不败 · 平局/小负赢半，49.9% 守住。",
        "hit": false,
        "outcome": "half_lose",
        "grade_note": "2-1 · 净胜 +1 · 输半"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2/2.5 @0.88",
        "reason_cn": "xG 约 2.9 vs 线 2.25 · 大 0.88 低水 · 2-1/1-1 路径。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "2-1 总3 · 线 2.25 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": false,
      "totals_hit": true,
      "spread_outcome": "half_lose",
      "totals_outcome": "full_win",
      "grade_note_spread": "2-1 · 净胜 +1 · 输半",
      "grade_note_totals": "2-1 总3 · 线 2.25 · 全赢",
      "actual_score": "2-1",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★大小球命中，让球盘未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m74": {
      "day": 19,
      "match": "Germany vs Paraguay",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "巴拉圭 +1.5 @0.85",
        "reason_cn": "精算诱上 · 升 -1.5 德高水 · 模型/市场守住 53% · 德国赢球≠穿盘。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "1-1 · 净胜 0 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5/3 @0.97",
        "reason_cn": "xG 2.54 vs 线 2.75 · 模型+盘面多数小球 · 1-0/2-0 路径。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "1-1 总2 · 线 2.75 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "full_win",
      "totals_outcome": "full_win",
      "grade_note_spread": "1-1 · 净胜 0 · 全赢",
      "grade_note_totals": "1-1 总2 · 线 2.75 · 全赢",
      "actual_score": "1-1",
      "outcome": {
        "key": "both_hit",
        "cn": "★大小球与让球盘均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m75": {
      "day": 19,
      "match": "Netherlands vs Morocco",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "摩洛哥 +0/0.5 @0.92",
        "reason_cn": "向模型退档 · 不败/赢半结构 · 50.3% 守住，edge 有限。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "1-1 · 净胜 0 · 赢半"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2/2.5 @0.95",
        "reason_cn": "模型 64.7% 超线 · 荷摩进攻属性 · 2-1/1-1 路径。",
        "hit": false,
        "outcome": "half_lose",
        "grade_note": "1-1 总2 · 线 2.25 · 输半"
      },
      "primary_hit": false,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "half_win",
      "totals_outcome": "half_lose",
      "grade_note_spread": "1-1 · 净胜 0 · 赢半",
      "grade_note_totals": "1-1 总2 · 线 2.25 · 输半",
      "actual_score": "1-1",
      "outcome": {
        "key": "primary_miss_secondary_hit",
        "cn": "★大小球未中，让球盘项命中",
        "analytics_cn": "倾向权重可能偏高——复盘时应优先看命中项，并反推是否应改倾向或降低倾向在决策中的权重",
        "primary_hit": false,
        "secondary_hit": true,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m78": {
      "day": 20,
      "match": "Côte d'Ivoire vs Norway",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "fav",
        "label_cn": "挪威 -0/0.5 @0.84",
        "reason_cn": "初→临档 -0/0.5 挺挪 · 0.84 低水 · xG 均势盘口偏挪 · 模型穿盘约 53%。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "1-2 · 净胜 -1 · 赢半"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5 @0.95",
        "reason_cn": "2.5 整球线 · 模型 xG 约 2.8 但临盘小 0.95 高水 · 副项 · 1-1/1-0 路径仍合理。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "1-2 总3 · 线 2.5 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "half_win",
      "totals_outcome": "full_lose",
      "grade_note_spread": "1-2 · 净胜 -1 · 赢半",
      "grade_note_totals": "1-2 总3 · 线 2.5 · 全输",
      "actual_score": "1-2",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m77": {
      "day": 20,
      "match": "France vs Sweden",
      "primary": "totals",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "dog",
        "label_cn": "瑞典 +1.5/2 @0.91",
        "reason_cn": "精算深盘但法0.98/瑞0.91均衡 · 模型53.3%穿盘。1-1→全赢；2-0→输半；3-0→全输；3-1→输半。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "3-0 · 净胜 +3 · 全输"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3.5 @0.83",
        "reason_cn": "公平线~2 · 现3.5高1.5球 · 超4球仅30.4%。2-0/3-0/2-1(总3)小全赢 · 3-1(总4)为精算反杀路径 · ★主项。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "3-0 总3 · 线 3.5 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": false,
      "totals_hit": true,
      "spread_outcome": "full_lose",
      "totals_outcome": "full_win",
      "grade_note_spread": "3-0 · 净胜 +3 · 全输",
      "grade_note_totals": "3-0 总3 · 线 3.5 · 全赢",
      "actual_score": "3-0",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★大小球命中，让球盘未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m79": {
      "day": 20,
      "match": "Mexico vs Ecuador",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "厄瓜多尔 +0/0.5 @1.02",
        "reason_cn": "墨 -0/0.5 临 0.87 升水 · 穿盘约 47% · 主场但未追深 · 受让结构。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-0 · 净胜 +2 · 全输"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 1.5/2 @0.83",
        "reason_cn": "1.5/2 大 0.83 低水续 · 模型 63% 超 1.75 · 2-0/2-1 路径 · ★主项。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "2-0 总2 · 线 1.75 · 赢半"
      },
      "primary_hit": true,
      "spread_hit": false,
      "totals_hit": true,
      "spread_outcome": "full_lose",
      "totals_outcome": "half_win",
      "grade_note_spread": "2-0 · 净胜 +2 · 全输",
      "grade_note_totals": "2-0 总2 · 线 1.75 · 赢半",
      "actual_score": "2-0",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★大小球命中，让球盘未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m80": {
      "day": 21,
      "match": "England vs Congo DR",
      "primary": "totals",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "dog",
        "label_cn": "刚果（金） +1.5 @0.93",
        "reason_cn": "blocker_inflate·英-1.5穿46.7%·1-0全赢/2-0全输 · 英0.96升水+轮换 · 模型53.3% · 副项。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "2-1 · 净胜 +1 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5 @0.85",
        "reason_cn": "初2.5→2/2.5大0.84→临2.5小0.85(线+水双收小) · 公平线~2 · 2-0仍小全赢 · 3球+小全输 · ★主项。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-1 总3 · 线 2.5 · 全输"
      },
      "primary_hit": false,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "full_win",
      "totals_outcome": "full_lose",
      "grade_note_spread": "2-1 · 净胜 +1 · 全赢",
      "grade_note_totals": "2-1 总3 · 线 2.5 · 全输",
      "actual_score": "2-1",
      "outcome": {
        "key": "primary_miss_secondary_hit",
        "cn": "★大小球未中，让球盘项命中",
        "analytics_cn": "倾向权重可能偏高——复盘时应优先看命中项，并反推是否应改倾向或降低倾向在决策中的权重",
        "primary_hit": false,
        "secondary_hit": true,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m81": {
      "day": 21,
      "match": "USA vs Bosnia & Herz.",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "波黑 +1.5 @0.86",
        "reason_cn": "美-1/1.5→-1.5@1.03高水 · 穿盘37%档 · 1-0·1-1·2-1全赢/2-0·3-0全输 · ★主项。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-0 · 净胜 +2 · 全输"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2.5/3 @0.82",
        "reason_cn": "大0.82再降水 · 小1.06升水 · 3球大赢半/4+全赢 · 副项。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-0 总2 · 线 2.75 · 全输"
      },
      "primary_hit": false,
      "spread_hit": false,
      "totals_hit": false,
      "spread_outcome": "full_lose",
      "totals_outcome": "full_lose",
      "grade_note_spread": "2-0 · 净胜 +2 · 全输",
      "grade_note_totals": "2-0 总2 · 线 2.75 · 全输",
      "actual_score": "2-0",
      "outcome": {
        "key": "both_miss",
        "cn": "★让球盘与大小球均未中",
        "analytics_cn": "全盘失误，需复盘模型、盘路与倾向规则",
        "primary_hit": false,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m82": {
      "day": 21,
      "match": "Belgium vs Senegal",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "dog",
        "label_cn": "塞内加尔 +0/0.5 @1.06",
        "reason_cn": "比-0.5→-0/0.5仍0.83 · 1-1赢半/0-0·0-1·塞全赢/比1-0·2-1·2-2赢半（90'） · 加时3-2不计盘 · ★主项。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "2-2 · 净胜 0 · 赢半"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2.5 @0.88",
        "reason_cn": "小1.00升水趋均衡 · 大0.88略低 · 模型超2.5约52% · 3球+全赢 · 副项。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "2-2 总4 · 线 2.5 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "half_win",
      "totals_outcome": "full_win",
      "grade_note_spread": "2-2 · 净胜 0 · 赢半",
      "grade_note_totals": "2-2 总4 · 线 2.5 · 全赢",
      "actual_score": "2-2",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m84": {
      "day": 22,
      "match": "Spain vs Austria",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "高信心",
      "spread": {
        "side": "fav",
        "label_cn": "西班牙 -1.5 @0.87",
        "reason_cn": "H1 vs J2 · -1.5 0.87 低水 · 2-0/3-0 穿盘路径 · 模型约58% · ★主项。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "3-0 · 净胜 +3 · 全赢"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2.5/3 @0.86",
        "reason_cn": "2.5→2.5/3升线+大0.86低水 · 3球大赢半/4+全赢 · 副项 · R9不打副项小。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "3-0 总3 · 线 2.75 · 赢半"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "full_win",
      "totals_outcome": "half_win",
      "grade_note_spread": "3-0 · 净胜 +3 · 全赢",
      "grade_note_totals": "3-0 总3 · 线 2.75 · 赢半",
      "actual_score": "3-0",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m83": {
      "day": 22,
      "match": "Portugal vs Croatia",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "dog",
        "label_cn": "克罗地亚 +0.5/1 @0.99",
        "reason_cn": "K2 vs L2 · 葡升-0.5/1仍0.99高水侧 · 1-1全赢/1-0输半/0-1全赢 · 模型守盘约54% · ★主项。",
        "hit": false,
        "outcome": "half_lose",
        "grade_note": "2-1 · 净胜 +1 · 输半"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2.5/3 @0.95",
        "reason_cn": "2/2.5→2.5/3升线 · 大0.95小0.93近均衡略偏大 · 副项 · R9不打副项小。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "2-1 总3 · 线 2.75 · 赢半"
      },
      "primary_hit": false,
      "spread_hit": false,
      "totals_hit": true,
      "spread_outcome": "half_lose",
      "totals_outcome": "half_win",
      "grade_note_spread": "2-1 · 净胜 +1 · 输半",
      "grade_note_totals": "2-1 总3 · 线 2.75 · 赢半",
      "actual_score": "2-1",
      "outcome": {
        "key": "primary_miss_secondary_hit",
        "cn": "★让球盘未中，大小球项命中",
        "analytics_cn": "倾向权重可能偏高——复盘时应优先看命中项，并反推是否应改倾向或降低倾向在决策中的权重",
        "primary_hit": false,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m85": {
      "day": 22,
      "match": "Switzerland vs Algeria",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "dog",
        "label_cn": "阿尔及利亚 +0.5 @0.91",
        "reason_cn": "瑞 -1→-0.5退档 · 阿+0.5@0.91低水 · 1-1/0-1全赢/1-0输 · 马赫雷斯反击轴 · ★主项。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "2-0 · 净胜 +2 · 全输"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2/2.5 @0.98",
        "reason_cn": "降线后大0.98高水=市场偏小球 · 仅作副项占位 · R9跳过副项小故不打小2/2.5。",
        "hit": false,
        "outcome": "half_lose",
        "grade_note": "2-0 总2 · 线 2.25 · 输半"
      },
      "primary_hit": false,
      "spread_hit": false,
      "totals_hit": false,
      "spread_outcome": "full_lose",
      "totals_outcome": "half_lose",
      "grade_note_spread": "2-0 · 净胜 +2 · 全输",
      "grade_note_totals": "2-0 总2 · 线 2.25 · 输半",
      "actual_score": "2-0",
      "outcome": {
        "key": "both_miss",
        "cn": "★让球盘与大小球均未中",
        "analytics_cn": "全盘失误，需复盘模型、盘路与倾向规则",
        "primary_hit": false,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m88": {
      "day": 23,
      "match": "Australia vs Egypt",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "fav",
        "label_cn": "澳大利亚 -0/0.5 @0.88",
        "reason_cn": "档位未翻，澳方降水低水 0.88、埃及受让抬到 1.01；模型 xG 1.45:1.15 偏澳，胜即全收、平仅输半 · ★主项。",
        "hit": false,
        "outcome": "half_lose",
        "grade_note": "1-1 · 净胜 0 · 输半"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2 @0.84",
        "reason_cn": "总线守在 2，小球持续低水 0.84；节奏预期偏谨慎，2 球可走水。",
        "hit": true,
        "outcome": "push",
        "grade_note": "1-1 总2 · 线 2 · 走水"
      },
      "primary_hit": false,
      "spread_hit": false,
      "totals_hit": true,
      "spread_outcome": "half_lose",
      "totals_outcome": "push",
      "grade_note_spread": "1-1 · 净胜 0 · 输半",
      "grade_note_totals": "1-1 总2 · 线 2 · 走水",
      "actual_score": "1-1",
      "outcome": {
        "key": "primary_miss_secondary_hit",
        "cn": "★让球盘未中，大小球项命中",
        "analytics_cn": "倾向权重可能偏高——复盘时应优先看命中项，并反推是否应改倾向或降低倾向在决策中的权重",
        "primary_hit": false,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m86": {
      "day": 23,
      "match": "Argentina vs Cape Verde",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "高信心",
      "spread": {
        "side": "dog",
        "label_cn": "佛得角 +2/2.5 @0.81",
        "reason_cn": "阿根廷虽然强势，但盘口已深到赢 3 才全收；让方升盘同时抬高水，更像限损盘。模型主路径 2-0/3-0，受让更稳 · ★主项。",
        "hit": true,
        "outcome": "half_win",
        "grade_note": "1-1 · 净胜 0 · 赢半"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3 @0.80",
        "reason_cn": "总线不升只压水，小球极低水；2-0、2-1、3-0 都是高频收尾，3 球还能走水。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "1-1 总2 · 线 3 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "spread_outcome": "half_win",
      "totals_outcome": "full_win",
      "grade_note_spread": "1-1 · 净胜 0 · 赢半",
      "grade_note_totals": "1-1 总2 · 线 3 · 全赢",
      "actual_score": "1-1",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m87": {
      "day": 23,
      "match": "Colombia vs Ghana",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "fav",
        "label_cn": "哥伦比亚 -0.5 @0.93",
        "reason_cn": "浅盘低水 · Kudus 反击有变数 · ★主项。",
        "hit": true,
        "outcome": "full_win",
        "grade_note": "1-0 · 净胜 +1 · 全赢"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2.5 @0.90",
        "reason_cn": "副项 · R9不打副项小。",
        "hit": false,
        "outcome": "full_lose",
        "grade_note": "1-0 总1 · 线 2.5 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "spread_outcome": "full_win",
      "totals_outcome": "full_lose",
      "grade_note_spread": "1-0 · 净胜 +1 · 全赢",
      "grade_note_totals": "1-0 总1 · 线 2.5 · 全输",
      "actual_score": "1-0",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    }
  }
};
