// Auto-generated by scripts/build-agent-stats.js — DO NOT EDIT
// Last updated: 2026-07-01T15:47:22+08:00
const AGENT_STATS = {
  "lastUpdated": "2026-07-01T15:47:22+08:00",
  "grade_rule_cn": "不败即中：全赢/赢半/走水算中，输半/全输算不中",
  "days_graded": 4,
  "days_pending": 1,
  "aggregate": {
    "spread": {
      "hit": 9,
      "miss": 4,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 69.2
    },
    "totals": {
      "hit": 7,
      "miss": 6,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 53.8
    },
    "primary": {
      "hit": 11,
      "miss": 2,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 84.6,
      "label_cn": "★倾向项"
    },
    "secondary": {
      "hit": 5,
      "miss": 8,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 38.5,
      "label_cn": "非倾向项"
    },
    "high_confidence": {
      "n": 8,
      "ids": [
        "m67",
        "m69",
        "m70",
        "m72",
        "m76",
        "m74",
        "m75",
        "m79"
      ],
      "spread": {
        "hit": 6,
        "miss": 2,
        "push": 0,
        "pending": 0,
        "n": 8,
        "pct": 75
      },
      "totals": {
        "hit": 4,
        "miss": 4,
        "push": 0,
        "pending": 0,
        "n": 8,
        "pct": 50
      },
      "primary": {
        "hit": 7,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "n": 8,
        "pct": 87.5
      }
    }
  },
  "days": [
    {
      "day": 17,
      "date": "2026-06-28",
      "graded_at": "2026-07-01T10:33:08.120Z",
      "spread": {
        "hit": 5,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "pct": 83.3,
        "n": 6
      },
      "totals": {
        "hit": 2,
        "miss": 4,
        "push": 0,
        "pending": 0,
        "pct": 33.3,
        "n": 6
      },
      "primary": {
        "hit": 5,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "pct": 83.3,
        "label_cn": "倾向项（★）",
        "n": 6
      },
      "high_confidence": {
        "n": 4,
        "ids": [
          "m67",
          "m69",
          "m70",
          "m72"
        ],
        "spread": {
          "hit": 4,
          "miss": 0,
          "pct": 100,
          "n": 4
        },
        "totals": {
          "hit": 1,
          "miss": 3,
          "pct": 25,
          "n": 4
        },
        "primary": {
          "hit": 4,
          "miss": 0,
          "pct": 100,
          "n": 4
        }
      }
    },
    {
      "day": 18,
      "date": "2026-06-29",
      "graded_at": "2026-07-01T10:19:39.397Z",
      "spread": {
        "hit": 1,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "pct": 100,
        "n": 1
      },
      "totals": {
        "hit": 1,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "pct": 100,
        "n": 1
      },
      "primary": {
        "hit": 1,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "pct": 100,
        "label_cn": "倾向项（★）",
        "n": 1
      },
      "high_confidence": null
    },
    {
      "day": 19,
      "date": "2026-06-30",
      "graded_at": "2026-07-01T10:19:39.421Z",
      "spread": {
        "hit": 2,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "pct": 66.7,
        "n": 3
      },
      "totals": {
        "hit": 2,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "pct": 66.7,
        "n": 3
      },
      "primary": {
        "hit": 2,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "pct": 66.7,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 3,
        "ids": [
          "m76",
          "m74",
          "m75"
        ],
        "spread": {
          "hit": 2,
          "miss": 1,
          "pct": 66.7,
          "n": 3
        },
        "totals": {
          "hit": 2,
          "miss": 1,
          "pct": 66.7,
          "n": 3
        },
        "primary": {
          "hit": 2,
          "miss": 1,
          "pct": 66.7,
          "n": 3
        }
      }
    },
    {
      "day": 20,
      "date": "2026-07-01",
      "graded_at": "2026-07-01T10:19:39.444Z",
      "spread": {
        "hit": 1,
        "miss": 2,
        "push": 0,
        "pending": 0,
        "pct": 33.3,
        "n": 3
      },
      "totals": {
        "hit": 2,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "pct": 66.7,
        "n": 3
      },
      "primary": {
        "hit": 3,
        "miss": 0,
        "push": 0,
        "pending": 0,
        "pct": 100,
        "label_cn": "倾向项（★）",
        "n": 3
      },
      "high_confidence": {
        "n": 1,
        "ids": [
          "m79"
        ],
        "spread": {
          "hit": 0,
          "miss": 1,
          "pct": 0,
          "n": 1
        },
        "totals": {
          "hit": 1,
          "miss": 0,
          "pct": 100,
          "n": 1
        },
        "primary": {
          "hit": 1,
          "miss": 0,
          "pct": 100,
          "n": 1
        }
      }
    }
  ],
  "pending": [
    {
      "day": 21,
      "date": "2026-07-02",
      "pick_ids": [
        "m80",
        "m81",
        "m82"
      ],
      "picks": [
        {
          "id": "m80",
          "match": "England vs Congo DR",
          "primary": "totals",
          "high_confidence": false,
          "confidence_cn": "中信心",
          "spread": {
            "side": "dog",
            "pick_cn": "刚果（金） +1.5 @0.93"
          },
          "totals": {
            "side": "under",
            "pick_cn": "小球 2.5 @0.85"
          }
        },
        {
          "id": "m81",
          "match": "USA vs Bosnia & Herz.",
          "primary": "spread",
          "high_confidence": true,
          "confidence_cn": "大信心",
          "spread": {
            "side": "dog",
            "pick_cn": "波黑 +1/1.5 @1.07"
          },
          "totals": {
            "side": "over",
            "pick_cn": "大球 2.5/3 @0.85"
          }
        },
        {
          "id": "m82",
          "match": "Belgium vs Senegal",
          "primary": "spread",
          "high_confidence": false,
          "confidence_cn": "中信心",
          "spread": {
            "side": "dog",
            "pick_cn": "塞内加尔 +0/0.5 @1.06"
          },
          "totals": {
            "side": "over",
            "pick_cn": "大球 2.5 @0.88"
          }
        }
      ]
    }
  ],
  "evaluation": {
    "label_cn": "Agent 双选评估",
    "match_count": 13,
    "grade_rule_cn": "不败即中：全赢/赢半/走水算中，输半/全输算不中",
    "spread": {
      "hit": 9,
      "miss": 4,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 69.2,
      "label_cn": "让球盘胜率",
      "desc_cn": "全部 13 场 Agent 双选 · 让球项"
    },
    "totals": {
      "hit": 7,
      "miss": 6,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 53.8,
      "label_cn": "大小盘胜率",
      "desc_cn": "全部 13 场 Agent 双选 · 大小项"
    },
    "primary": {
      "hit": 11,
      "miss": 2,
      "push": 0,
      "pending": 0,
      "n": 13,
      "pct": 84.6,
      "label_cn": "倾向盘胜率",
      "desc_cn": "每场标★方向（让球或大小）"
    },
    "high_confidence": {
      "match_count": 8,
      "ids": [
        "m67",
        "m69",
        "m70",
        "m72",
        "m76",
        "m74",
        "m75",
        "m79"
      ],
      "primary": {
        "hit": 7,
        "miss": 1,
        "push": 0,
        "pending": 0,
        "n": 8,
        "pct": 87.5,
        "label_cn": "大信心胜率",
        "desc_cn": "大信心场 · ★倾向项命中率"
      }
    }
  },
  "knockout": {
    "label_cn": "32强 · Agent 双选",
    "match_count": 13,
    "ids": [
      "m67",
      "m68",
      "m69",
      "m70",
      "m71",
      "m72",
      "m73",
      "m74",
      "m75",
      "m76",
      "m77",
      "m78",
      "m79"
    ],
    "spread": {
      "hit": 9,
      "miss": 4,
      "n": 13,
      "pct": 69.2
    },
    "totals": {
      "hit": 7,
      "miss": 6,
      "n": 13,
      "pct": 53.8
    },
    "primary": {
      "hit": 11,
      "miss": 2,
      "n": 13,
      "pct": 84.6,
      "label_cn": "★倾向项"
    },
    "both_hit": {
      "n": 4,
      "pct": 30.8
    },
    "at_least_one": {
      "n": 12,
      "pct": 92.3
    },
    "all_legs": {
      "hit": 16,
      "n": 26,
      "pct": 61.5
    }
  },
  "byId": {
    "m67": {
      "day": 17,
      "match": "Panama vs England",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "巴拿马 +2/2.5 @1.02",
        "reason_cn": "FIFA 官方英格兰 5 轮换（Rice/Mainoo/Foden 替补）；xG 客 2.08→1.90。胜约 65% 但穿 -2.25 约 25%；0-1/0-2 仍守住。",
        "hit": true,
        "grade_note": "0-2 · 净胜 -2 · 赢半"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3/3.5",
        "reason_cn": "模型公允总进球约 2.0，现线 3.25 偏高约 0.75 球；超线概率约 40%，小水 1.02 在卖大球叙事。",
        "hit": true,
        "grade_note": "0-2 总2 · 线 3.25 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "grade_note_spread": "0-2 · 净胜 -2 · 赢半",
      "grade_note_totals": "0-2 总2 · 线 3.25 · 全赢",
      "actual_score": "0-2",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m68": {
      "day": 17,
      "match": "Croatia vs Ghana",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "dog",
        "label_cn": "加纳 +0.5 守住",
        "reason_cn": "加纳 4 分已锁前二可接受平局；克罗地亚 3 分须胜易急躁；xG 1.42 vs 1.38 均势，首推 1-1。",
        "hit": false,
        "grade_note": "2-1 · 净胜 +1 · 全输"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2",
        "reason_cn": "2 整球线下 ≤2 球即全赢；模型有平局/小胜路径，大球 0.86 略诱但出线博弈下闷战概率不低。",
        "hit": false,
        "grade_note": "2-1 总3 · 线 2 · 全输"
      },
      "primary_hit": false,
      "spread_hit": false,
      "totals_hit": false,
      "grade_note_spread": "2-1 · 净胜 +1 · 全输",
      "grade_note_totals": "2-1 总3 · 线 2 · 全输",
      "actual_score": "2-1",
      "outcome": {
        "key": "both_miss",
        "cn": "★让球盘与大小球均未中",
        "analytics_cn": "全盘失误，需复盘模型、盘路与倾向规则",
        "primary_hit": false,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m69": {
      "day": 17,
      "match": "Algeria vs Austria",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "fav",
        "label_cn": "奥地利 PK（-0）@0.84",
        "reason_cn": "已锁前二 · 输球亦出线；阿尔须胜但模型平局 +9% → 不败约 73%。无输半档，符合先不输。",
        "hit": true,
        "grade_note": "3-3 · 净胜 0 · 走水"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 1.5/2 @0.82",
        "reason_cn": "副项 · 皇冠小 0.82 + 默契战；但 1-1 输半、模型约 68% 超线，不作★。",
        "hit": false,
        "grade_note": "3-3 总6 · 线 1.75 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "grade_note_spread": "3-3 · 净胜 0 · 走水",
      "grade_note_totals": "3-3 总6 · 线 1.75 · 全输",
      "actual_score": "3-3",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m70": {
      "day": 17,
      "match": "Jordan vs Argentina",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "约旦 +2/2.5 守住",
        "reason_cn": "阿根廷 6 分已出线必轮换；模型胜 77% 但穿 -2.25 校准后约 49%；升盘 0.99 为限损而非加强。",
        "hit": true,
        "grade_note": "1-3 · 净胜 -2 · 赢半"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3",
        "reason_cn": "3 整球走水多；大球 0.83 便宜但模型公允约 2.75，轮换队常见 2-0/3-0 卡线而非开放对攻。",
        "hit": false,
        "grade_note": "1-3 总4 · 线 3 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "grade_note_spread": "1-3 · 净胜 -2 · 赢半",
      "grade_note_totals": "1-3 总4 · 线 3 · 全输",
      "actual_score": "1-3",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m71": {
      "day": 17,
      "match": "Colombia vs Portugal",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "dog",
        "label_cn": "哥伦比亚 +0.5 守住",
        "reason_cn": "哥伦 6 分平局即头名；葡萄牙 4 分须胜但 0.98 抬水未追；xG 1.55 vs 1.58 均势。",
        "hit": true,
        "grade_note": "0-0 · 净胜 0 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5/3",
        "reason_cn": "已出线双方 xG 略降；小水 0.89 偏小，迈阿密湿热下更可能 1-1/2-1 而非开放对攻。",
        "hit": true,
        "grade_note": "0-0 总0 · 线 2.75 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "grade_note_spread": "0-0 · 净胜 0 · 全赢",
      "grade_note_totals": "0-0 总0 · 线 2.75 · 全赢",
      "actual_score": "0-0",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m72": {
      "day": 17,
      "match": "Congo DR vs Uzbekistan",
      "primary": "spread",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "fav",
        "label_cn": "刚果(金) -0.5/1",
        "reason_cn": "双方须胜无控分；盘口向 xG 1.48 vs 0.72 修正，刚果 -0.75 与模型一致，主场生死战信实力方小胜。",
        "hit": true,
        "grade_note": "3-1 · 净胜 +2 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2/2.5",
        "reason_cn": "xG 合计约 2.2，线 2.25 中性；乌兹别克守势下 1-0/2-0 比大比分更合理。",
        "hit": false,
        "grade_note": "3-1 总4 · 线 2.25 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "grade_note_spread": "3-1 · 净胜 +2 · 全赢",
      "grade_note_totals": "3-1 总4 · 线 2.25 · 全输",
      "actual_score": "3-1",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m73": {
      "day": 18,
      "match": "South Africa vs Canada",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "dog",
        "label_cn": "南非 +0/0.5 @0.98",
        "reason_cn": "A 组次席 4 分出线 · 小组赛 2 失球偏稳；加拿大须破局但 -0/0.5 低水未必穿。模型平局约 32%。",
        "hit": true,
        "grade_note": "0-1 · 净胜 -1 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2/2.5",
        "reason_cn": "32 强首轮双方偏谨慎 · 模型总 xG 约 2.1 · 2/2.5 线下 ≤2 球即全赢。",
        "hit": true,
        "grade_note": "0-1 总1 · 线 2.25 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "grade_note_spread": "0-1 · 净胜 -1 · 全赢",
      "grade_note_totals": "0-1 总1 · 线 2.25 · 全赢",
      "actual_score": "0-1",
      "outcome": {
        "key": "both_hit",
        "cn": "★让球盘与大小球均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m76": {
      "day": 19,
      "match": "Brazil vs Japan",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "日本 +0.5/1 @0.88",
        "reason_cn": "巴西 0.96 仍高水 · 日本 F 组不败 · 平局/小负赢半，49.9% 守住。",
        "hit": false,
        "grade_note": "2-1 · 净胜 +1 · 输半"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2/2.5 @0.88",
        "reason_cn": "xG 约 2.9 vs 线 2.25 · 大 0.88 低水 · 2-1/1-1 路径。",
        "hit": true,
        "grade_note": "2-1 总3 · 线 2.25 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": false,
      "totals_hit": true,
      "grade_note_spread": "2-1 · 净胜 +1 · 输半",
      "grade_note_totals": "2-1 总3 · 线 2.25 · 全赢",
      "actual_score": "2-1",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★大小球命中，让球盘未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m74": {
      "day": 19,
      "match": "Germany vs Paraguay",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "巴拉圭 +1.5 @0.85",
        "reason_cn": "精算诱上 · 升 -1.5 德高水 · 模型/市场守住 53% · 德国赢球≠穿盘。",
        "hit": true,
        "grade_note": "1-1 · 净胜 0 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5/3 @0.97",
        "reason_cn": "xG 2.54 vs 线 2.75 · 模型+盘面多数小球 · 1-0/2-0 路径。",
        "hit": true,
        "grade_note": "1-1 总2 · 线 2.75 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": true,
      "grade_note_spread": "1-1 · 净胜 0 · 全赢",
      "grade_note_totals": "1-1 总2 · 线 2.75 · 全赢",
      "actual_score": "1-1",
      "outcome": {
        "key": "both_hit",
        "cn": "★大小球与让球盘均命中",
        "analytics_cn": "倾向正确，双项验证通过",
        "primary_hit": true,
        "secondary_hit": true,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m75": {
      "day": 19,
      "match": "Netherlands vs Morocco",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "摩洛哥 +0/0.5 @0.92",
        "reason_cn": "向模型退档 · 不败/赢半结构 · 50.3% 守住，edge 有限。",
        "hit": true,
        "grade_note": "1-1 · 净胜 0 · 赢半"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 2/2.5 @0.95",
        "reason_cn": "模型 64.7% 超线 · 荷摩进攻属性 · 2-1/1-1 路径。",
        "hit": false,
        "grade_note": "1-1 总2 · 线 2.25 · 输半"
      },
      "primary_hit": false,
      "spread_hit": true,
      "totals_hit": false,
      "grade_note_spread": "1-1 · 净胜 0 · 赢半",
      "grade_note_totals": "1-1 总2 · 线 2.25 · 输半",
      "actual_score": "1-1",
      "outcome": {
        "key": "primary_miss_secondary_hit",
        "cn": "★大小球未中，让球盘项命中",
        "analytics_cn": "倾向权重可能偏高——复盘时应优先看命中项，并反推是否应改倾向或降低倾向在决策中的权重",
        "primary_hit": false,
        "secondary_hit": true,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m78": {
      "day": 20,
      "match": "Côte d'Ivoire vs Norway",
      "primary": "spread",
      "high_confidence": false,
      "confidence_cn": null,
      "spread": {
        "side": "fav",
        "label_cn": "挪威 -0/0.5 @0.84",
        "reason_cn": "初→临档 -0/0.5 挺挪 · 0.84 低水 · xG 均势盘口偏挪 · 模型穿盘约 53%。",
        "hit": true,
        "grade_note": "1-2 · 净胜 -1 · 全赢"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 2.5 @0.95",
        "reason_cn": "2.5 整球线 · 模型 xG 约 2.8 但临盘小 0.95 高水 · 副项 · 1-1/1-0 路径仍合理。",
        "hit": false,
        "grade_note": "1-2 总3 · 线 2.5 · 全输"
      },
      "primary_hit": true,
      "spread_hit": true,
      "totals_hit": false,
      "grade_note_spread": "1-2 · 净胜 -1 · 全赢",
      "grade_note_totals": "1-2 总3 · 线 2.5 · 全输",
      "actual_score": "1-2",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★让球盘命中，大小球未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "spread",
        "secondary_market": "totals"
      }
    },
    "m77": {
      "day": 20,
      "match": "France vs Sweden",
      "primary": "totals",
      "high_confidence": false,
      "confidence_cn": "中信心",
      "spread": {
        "side": "dog",
        "label_cn": "瑞典 +1.5/2 @0.91",
        "reason_cn": "精算深盘但法0.98/瑞0.91均衡 · 模型53.3%穿盘。1-1→全赢；2-0→输半；3-0→全输；3-1→输半。",
        "hit": false,
        "grade_note": "3-0 · 净胜 +3 · 全输"
      },
      "totals": {
        "side": "under",
        "label_cn": "小球 3.5 @0.83",
        "reason_cn": "公平线~2 · 现3.5高1.5球 · 超4球仅30.4%。2-0/3-0/2-1(总3)小全赢 · 3-1(总4)为精算反杀路径 · ★主项。",
        "hit": true,
        "grade_note": "3-0 总3 · 线 3.5 · 全赢"
      },
      "primary_hit": true,
      "spread_hit": false,
      "totals_hit": true,
      "grade_note_spread": "3-0 · 净胜 +3 · 全输",
      "grade_note_totals": "3-0 总3 · 线 3.5 · 全赢",
      "actual_score": "3-0",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★大小球命中，让球盘未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    },
    "m79": {
      "day": 20,
      "match": "Mexico vs Ecuador",
      "primary": "totals",
      "high_confidence": true,
      "confidence_cn": "大信心",
      "spread": {
        "side": "dog",
        "label_cn": "厄瓜多尔 +0/0.5 @1.02",
        "reason_cn": "墨 -0/0.5 临 0.87 升水 · 穿盘约 47% · 主场但未追深 · 受让结构。",
        "hit": false,
        "grade_note": "2-0 · 净胜 +2 · 全输"
      },
      "totals": {
        "side": "over",
        "label_cn": "大球 1.5/2 @0.83",
        "reason_cn": "1.5/2 大 0.83 低水续 · 模型 63% 超 1.75 · 2-0/2-1 路径 · ★主项。",
        "hit": true,
        "grade_note": "2-0 总2 · 线 1.75 · 赢半"
      },
      "primary_hit": true,
      "spread_hit": false,
      "totals_hit": true,
      "grade_note_spread": "2-0 · 净胜 +2 · 全输",
      "grade_note_totals": "2-0 总2 · 线 1.75 · 赢半",
      "actual_score": "2-0",
      "outcome": {
        "key": "primary_hit_secondary_miss",
        "cn": "★大小球命中，让球盘未中",
        "analytics_cn": "倾向正确；非倾向项失误，可降权备用项展示",
        "primary_hit": true,
        "secondary_hit": false,
        "primary_market": "totals",
        "secondary_market": "spread"
      }
    }
  }
};
