// Auto-generated by update-data.js — DO NOT EDIT MANUALLY
// Updated: 2026-06-15T11:39:26.028Z
const LIVE_DATA = {
  "lastUpdated": "2026-06-15T11:39:26.028Z",
  "todayDate": "2026-06-15",
  "fixtures": [],
  "allResults": [],
  "standings": [],
  "injuries": {},
  "yesterdayResults": []
};
