// Auto-generated by update-data.js — DO NOT EDIT MANUALLY
// Updated: 2026-06-12T08:12:49.095Z
const LIVE_DATA = {
  "lastUpdated": "2026-06-12T08:12:49.095Z",
  "todayDate": "2026-06-12",
  "fixtures": [],
  "allResults": [],
  "standings": [],
  "injuries": {},
  "yesterdayResults": []
};
