// Auto-generated by update-data.js — DO NOT EDIT MANUALLY
// This file is updated daily at 08:00 Beijing time via GitHub Actions
// Manual placeholder until first API run
const LIVE_DATA = {
  "lastUpdated": "2026-06-09T00:00:00.000Z",
  "todayDate": "2026-06-09",
  "fixtures": [],
  "standings": [],
  "injuries": {},
  "yesterdayResults": []
};
