/**
 * Daily / scheduled sync from API-Football
 * Updates: js/live-data.js + js/matches-data.js (todayMatches, injuries, predictions, results)
 *
 * Usage: API_KEY=xxx node scripts/update-data.js
 */

const https = require('https');
const fs    = require('fs');
const path  = require('path');

const API_KEY   = process.env.API_KEY || '';
const LEAGUE_ID = 1;
const SEASON    = 2026;
const BASE_URL  = 'v3.football.api-sports.io';
const ROOT      = path.join(__dirname, '..');
const LIVE_PATH = path.join(ROOT, 'js', 'live-data.js');
const MATCH_PATH = path.join(ROOT, 'js', 'matches-data.js');

const TEAM_CANON = {
  'mexico': 'Mexico',
  'south africa': 'South Africa',
  'korea republic': 'South Korea',
  'south korea': 'South Korea',
  'czechia': 'Czechia',
  'czech republic': 'Czechia',
  'usa': 'USA',
  'united states': 'USA',
  'turkiye': 'Türkiye',
  'turkey': 'Türkiye',
  "cote d'ivoire": "Côte d'Ivoire",
  'ivory coast': "Côte d'Ivoire",
  'bosnia and herzegovina': 'Bosnia & Herz.',
  'bosnia & herzegovina': 'Bosnia & Herz.',
  'congo dr': 'Congo DR',
  'dr congo': 'Congo DR',
  'cape verde': 'Cape Verde',
  'curacao': 'Curaçao',
  'iran': 'Iran',
  'ir iran': 'Iran',
};

function canonTeam(name) {
  if (!name) return '';
  const k = name.toLowerCase().trim();
  return TEAM_CANON[k] || name;
}

function beijingDate(offsetDays = 0) {
  const t = new Date(Date.now() + 8 * 3600 * 1000 + offsetDays * 86400000);
  const y = t.getUTCFullYear();
  const m = String(t.getUTCMonth() + 1).padStart(2, '0');
  const d = String(t.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

function apiRequest(endpoint) {
  return new Promise((resolve, reject) => {
    const options = {
      hostname: BASE_URL,
      path: `/v3/${endpoint}`,
      method: 'GET',
      headers: { 'x-apisports-key': API_KEY },
    };
    const req = https.request(options, res => {
      let data = '';
      res.on('data', c => (data += c));
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.errors && Object.keys(parsed.errors).length) {
            console.warn('API warning:', JSON.stringify(parsed.errors));
          }
          resolve(parsed);
        } catch (e) {
          reject(new Error('JSON parse error: ' + data.slice(0, 200)));
        }
      });
    });
    req.on('error', reject);
    req.setTimeout(20000, () => req.destroy(new Error('Timeout')));
    req.end();
  });
}

function loadMatchData() {
  const raw = fs.readFileSync(MATCH_PATH, 'utf8');
  const fn = new Function(raw + '\nreturn MATCH_DATA;');
  return fn();
}

function saveMatchData(data) {
  const ts = new Date().toISOString();
  fs.writeFileSync(
    MATCH_PATH,
    `// Auto-synced by scripts/update-data.js — manual edits may be overwritten on next sync\n` +
      `// Last API sync: ${ts}\n` +
      `const MATCH_DATA = ${JSON.stringify(data, null, 2)};\n`
  );
}

function saveLiveData(obj) {
  fs.writeFileSync(
    LIVE_PATH,
    `// Auto-generated by update-data.js — DO NOT EDIT MANUALLY\n` +
      `// Updated: ${obj.lastUpdated}\n` +
      `const LIVE_DATA = ${JSON.stringify(obj, null, 2)};\n`
  );
}

function parsePercent(v) {
  if (v == null) return null;
  const n = parseInt(String(v).replace('%', ''), 10);
  return Number.isFinite(n) ? n : null;
}

function fixtureToLite(f) {
  return {
    id: f.fixture?.id,
    status: f.fixture?.status?.short,
    elapsed: f.fixture?.status?.elapsed,
    date: f.fixture?.date,
    home: canonTeam(f.teams?.home?.name),
    away: canonTeam(f.teams?.away?.name),
    home_id: f.teams?.home?.id,
    away_id: f.teams?.away?.id,
    home_score: f.goals?.home,
    away_score: f.goals?.away,
    venue: f.fixture?.venue?.name,
    city: f.fixture?.venue?.city,
    round: f.league?.round,
  };
}

function matchTeams(fixture, m) {
  const h = canonTeam(fixture.home);
  const a = canonTeam(fixture.away);
  return h === m.home.name && a === m.away.name;
}

function findFixtureForMatch(allFixtures, m) {
  return allFixtures.find(f => matchTeams(f, m));
}

async function fetchAllFixtures() {
  const dates = [beijingDate(-1), beijingDate(0), beijingDate(1)];
  const map = new Map();

  const ingest = (list, label) => {
    (list || []).forEach(f => {
      const lite = fixtureToLite(f);
      if (lite.id) map.set(lite.id, { raw: f, lite });
    });
    console.log(`   → ${(list || []).length} match(es) ${label ? `(${label})` : ''}`);
  };

  for (const d of dates) {
    console.log(`📡 Fixtures for ${d} (Beijing)...`);
    try {
      const res = await apiRequest(
        `fixtures?league=${LEAGUE_ID}&season=${SEASON}&date=${d}&timezone=Asia/Shanghai`
      );
      ingest(res.response, d);
    } catch (e) {
      console.warn(`   ⚠ ${d}: ${e.message}`);
    }
    await sleep(350);
  }

  if (map.size === 0) {
    const from = beijingDate(-3);
    const to = beijingDate(2);
    console.log(`📡 Fallback range ${from} → ${to}...`);
    try {
      const res = await apiRequest(
        `fixtures?league=${LEAGUE_ID}&season=${SEASON}&from=${from}&to=${to}&timezone=Asia/Shanghai`
      );
      ingest(res.response, 'range');
    } catch (e) {
      console.warn(`   ⚠ range: ${e.message}`);
    }
    await sleep(350);
  }

  if (map.size === 0) {
    console.log('📡 Fallback: full season fixtures (filter by todayMatches teams)...');
    try {
      const data = loadMatchData();
      const teamSet = new Set();
      data.todayMatches.forEach(m => {
        teamSet.add(m.home.name);
        teamSet.add(m.away.name);
      });
      const res = await apiRequest(`fixtures?league=${LEAGUE_ID}&season=${SEASON}`);
      const matched = (res.response || []).filter(f => {
        const h = canonTeam(f.teams?.home?.name);
        const a = canonTeam(f.teams?.away?.name);
        return teamSet.has(h) && teamSet.has(a);
      });
      ingest(matched, 'season+teams');
    } catch (e) {
      console.warn(`   ⚠ season: ${e.message}`);
    }
  }

  return [...map.values()];
}

async function fetchPrediction(fixtureId) {
  try {
    const res = await apiRequest(`predictions?fixture=${fixtureId}`);
    return res.response?.[0] || null;
  } catch {
    return null;
  }
}

async function fetchTeamInjuries(teamId) {
  try {
    const res = await apiRequest(
      `injuries?league=${LEAGUE_ID}&season=${SEASON}&team=${teamId}`
    );
    return res.response || [];
  } catch {
    return [];
  }
}

function mapInjuries(apiList) {
  if (!apiList.length) return null;
  return apiList.slice(0, 8).map(i => ({
    player: i.player?.name || 'Unknown',
    status: /out|missing|suspended/i.test(i.player?.reason || i.type || '')
      ? 'OUT'
      : 'DOUBT',
    note: i.player?.reason || i.type || '伤病观察',
    confirmed: false,
  }));
}

function applyPrediction(match, pred) {
  if (!pred?.predictions) return;
  const p = pred.predictions;
  const pct = p.percent || {};
  const hw = parsePercent(pct.home);
  const dr = parsePercent(pct.draw);
  const aw = parsePercent(pct.away);
  if (hw != null) match.prediction.home_win = hw;
  if (dr != null) match.prediction.draw = dr;
  if (aw != null) match.prediction.away_win = aw;

  const advice = p.advice || pred.advice || '';
  const winner = p.winner?.name;
  if (advice) {
    match.prediction.key_factor =
      `API 模型综合：${advice}${winner ? ` · 倾向 ${canonTeam(winner)}` : ''}（数据娱乐推演，不代表真实赛果）`;
  }

  const goals = p.goals;
  if (goals?.home != null && goals?.away != null) {
    const gh = String(goals.home).replace(/[^0-9.-]/g, '');
    const ga = String(goals.away).replace(/[^0-9.-]/g, '');
    if (gh && ga && !gh.includes('.') && !ga.includes('.')) {
      match.prediction.score = `${gh}-${ga}`;
    }
  }

  if (pred.comparison?.total?.home && pred.comparison?.total?.away) {
    const th = parseFloat(pred.comparison.total.home);
    const ta = parseFloat(pred.comparison.total.away);
    if (th && ta) {
      match.prediction.confidence = Math.min(
        95,
        Math.round(Math.max(th, ta) * 0.9)
      );
    }
  }
}

function applyResult(match, lite) {
  const st = lite.status;
  const finished = ['FT', 'AET', 'PEN'].includes(st);
  if (lite.home_score == null || lite.away_score == null) return;

  match.actualResult = {
    home_score: lite.home_score,
    away_score: lite.away_score,
    status: st,
    label: finished ? '全场结束' : st === 'HT' ? '中场' : st,
  };

  if (finished) {
    match.prediction.score = `${lite.home_score}-${lite.away_score}`;
    match.note = (match.note || '').replace(/· 待赛.*/, '') +
      ` · 已结束 ${lite.home_score}-${lite.away_score}`;
  }
}

function prependResultNews(data, fixtures) {
  const finished = fixtures
    .map(x => x.lite)
    .filter(f => ['FT', 'AET', 'PEN'].includes(f.status));

  finished.forEach(f => {
    const text = `🏁 赛果 · ${f.home} ${f.home_score}-${f.away_score} ${f.away} · 数据来源 API 官方同步`;
    const exists = data.breakingNews.some(n => n.text.includes(`${f.home_score}-${f.away_score}`) && n.text.includes(f.home));
    if (!exists) {
      data.breakingNews.unshift({
        tag: 'OFFICIAL',
        text,
        time: '最新赛果',
      });
    }
  });
  data.breakingNews = data.breakingNews.slice(0, 12);
}

async function syncMatchesData(allFixtures) {
  const data = loadMatchData();
  data.lastUpdated = new Date().toISOString();
  data.syncSource = 'API-Football';

  let apiCalls = 0;

  for (const m of data.todayMatches) {
    const hit = findFixtureForMatch(
      allFixtures.map(x => x.lite),
      m
    );
    if (!hit) {
      console.log(`   ○ No API fixture: ${m.home.name} vs ${m.away.name}`);
      continue;
    }

    console.log(`   ● Sync ${m.home.name} vs ${m.away.name} [${hit.status}]`);

    applyResult(m, hit);

    if (hit.home_id) {
      const injH = await fetchTeamInjuries(hit.home_id);
      apiCalls++;
      await sleep(300);
      const mapped = mapInjuries(injH);
      if (mapped?.length) m.home.injuries = mapped;
    }
    if (hit.away_id) {
      const injA = await fetchTeamInjuries(hit.away_id);
      apiCalls++;
      await sleep(300);
      const mapped = mapInjuries(injA);
      if (mapped?.length) m.away.injuries = mapped;
    }

    if (hit.id && !['FT', 'AET', 'PEN'].includes(hit.status)) {
      const pred = await fetchPrediction(hit.id);
      apiCalls++;
      await sleep(350);
      if (pred) applyPrediction(m, pred);
    } else if (hit.id && ['FT', 'AET', 'PEN'].includes(hit.status)) {
      m.prediction.key_factor =
        `比赛已结束，最终比分 ${hit.home_score}-${hit.away_score}。以上为赛前模型娱乐推演存档，实际赛果以官方为准。`;
    }
  }

  prependResultNews(data, allFixtures);
  saveMatchData(data);
  console.log(`✅ matches-data.js updated (${apiCalls} extra API calls for predictions/injuries)`);
  return data;
}

async function main() {
  if (!API_KEY) {
    console.error('❌ API_KEY not set.');
    console.error('   GitHub: Settings → Secrets → API_FOOTBALL_KEY');
    console.error('   Local:  set API_KEY=your_key && node scripts/update-data.js');
    process.exit(1);
  }

  console.log('🔄 API sync start —', new Date().toISOString());
  console.log('📅 Beijing today:', beijingDate(0));

  const allFixtures = await fetchAllFixtures();
  const lites = allFixtures.map(x => x.lite);

  const injuries = {};
  const teamIds = new Set();
  lites.forEach(f => {
    if (f.home_id) teamIds.add(f.home_id);
    if (f.away_id) teamIds.add(f.away_id);
  });

  let standings = [];
  try {
    const standData = await apiRequest(`standings?league=${LEAGUE_ID}&season=${SEASON}`);
    standings = standData.response?.[0]?.league?.standings || [];
    console.log(`✅ Standings groups: ${standings.length}`);
  } catch (e) {
    console.warn('⚠ Standings:', e.message);
  }

  await syncMatchesData(allFixtures);

  const liveObj = {
    lastUpdated: new Date().toISOString(),
    todayDate: beijingDate(0),
    fixtures: lites,
    allResults: lites.filter(f => ['FT', 'AET', 'PEN'].includes(f.status)),
    standings: standings.map(grp =>
      Array.isArray(grp)
        ? grp.map(t => ({
            group: t.group,
            team: canonTeam(t.team?.name),
            rank: t.rank,
            pts: t.points,
            played: t.all?.played,
            win: t.all?.win,
            draw: t.all?.draw,
            lose: t.all?.lose,
            gf: t.all?.goals?.for,
            ga: t.all?.goals?.against,
            gd: t.goalsDiff,
          }))
        : []
    ),
    injuries,
    yesterdayResults: lites
      .filter(f => ['FT', 'AET', 'PEN'].includes(f.status))
      .map(f => ({
        home: f.home,
        away: f.away,
        score: `${f.home_score}-${f.away_score}`,
        status: f.status,
      })),
  };

  saveLiveData(liveObj);
  console.log('✅ live-data.js written');

  console.log('\n═══ SUMMARY ═══');
  console.log('Fixtures fetched:', lites.length);
  lites.forEach(f =>
    console.log(`  ${f.home} ${f.home_score ?? '-'}:${f.away_score ?? '-'} ${f.away} [${f.status}]`)
  );
  console.log('Finished:       ', liveObj.allResults.length);
  console.log('════════════════\n');
}

main().catch(e => {
  console.error('❌ Fatal:', e);
  process.exit(1);
});
